spring:
  application:
    name: relboard-crawler

  config:
    import:
      - classpath:application-db.yml
      - classpath:application-crawler.yml
      - classpath:application-log.yml

  profiles:
    active: ${PROFILE:local}

logging:
  level:
    org.flywaydb: INFO
