version: '3.8'

services:
  relboard-crawler:
    image: ${CRAWLER_IMAGE}
    container_name: relboard-crawler
    env_file:
      - ./app.env
    ports:
      - "8080:8080"
    depends_on:
      - relboard-cralwer-mysql
      - relboard-zookeeper
    restart: unless-stopped
    networks:
      - relboard-network
      - relboard_extern_network

  relboard-cralwer-mysql:
    image: mysql:8.4
    container_name: relboard-crawler-mysql
    env_file:
      - ./.env
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - relboard_crawler_mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-p${MYSQL_ROOT_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - relboard-network

  relboard-zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: relboard-crawler-zk
    env_file:
      - ./.env
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: ${ZOOKEEPER_CLIENT_PORT}
      ZOOKEEPER_TICK_TIME: ${ZOOKEEPER_TICK_TIME}
    volumes:
      - relboard_crawler_zookeeper_data:/var/lib/zookeeper/data
      - relboard_crawler_zookeeper_log:/var/lib/zookeeper/log
    networks:
      - relboard-network

  relboard-kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: relboard-crawler-kafka
    env_file:
      - ./.env
    depends_on:
      - relboard-zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: ${KAFKA_BROKER_ID}
      KAFKA_ZOOKEEPER_CONNECT: ${KAFKA_ZOOKEEPER_CONNECT}
      KAFKA_ADVERTISED_LISTENERS: ${KAFKA_ADVERTISED_LISTENERS}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: ${KAFKA_LISTENER_SECURITY_PROTOCOL_MAP}
      KAFKA_INTER_BROKER_LISTENER_NAME: ${KAFKA_INTER_BROKER_LISTENER_NAME}
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: ${KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR}
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: ${KAFKA_TRANSACTION_STATE_LOG_MIN_ISR}
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: ${KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR}
    volumes:
      - relboard_crawler_kafka_data:/var/lib/kafka/data
    networks:
      - relboard_extern_network
      - relboard-network

volumes:
  relboard_crawler_mysql_data:
  relboard_crawler_zookeeper_data:
  relboard_crawler_zookeeper_log:
  relboard_crawler_kafka_data:


networks:
  relboard_extern_network:
    external: true
  relboard-network:
    driver: bridge
