spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${DATABASE_DDL_AUTO}
    generate-ddl: false
    open-in-view: false
    properties:
      hibernate:
        dialect: ${HIBERNATE_DIALECT:org.hibernate.dialect.MySQLDialect}
  flyway:
    enabled: true
    locations: classpath:migration
    baseline-on-migrate: true       # 기존 DB에 이미 테이블이 있더라도 시작 가능
    validate-on-migrate: true       # 변경된 스키마 검증
    clean-disabled: true            # 운영에서 drop 방지
    out-of-order: false             # 버전 순서 보장
    encoding: UTF-8
