spring:
  application:
    name: relboard-crawler

  jackson:
    serialization:
      write-dates-as-timestamps: false

  config:
    import:
      - classpath:application-db.yml
      - classpath:application-crawler.yml
      - classpath:application-log.yml
      - classpath:application-kafka.yml

  profiles:
    active: ${PROFILE:local}

logging:
  level:
    org.flywaydb: INFO
